import type { Thread } from "./types";

const BASE = Date.now();
const h = (hours: number) => new Date(BASE - hours * 3_600_000).toISOString();
const inDays = (days: number) =>
  new Date(BASE + days * 86_400_000).toISOString().slice(0, 10);

const FACULTY = "Dr. Ayesha Rahman";

/**
 * Sample triaged inbox. Shape mirrors what the triage API will return, so this
 * file can be swapped for a network call without touching components.
 */
export const MOCK_THREADS: Thread[] = [
  {
    id: "t-001",
    subject: "Re-evaluation request — CSE 3201 Midterm (ID 19203045)",
    participants: ["Nafis Iqbal", FACULTY],
    lastMessagePreview:
      "Sir, I believe question 4 was marked incorrectly. The re-evaluation window closes Friday.",
    lastMessageAt: h(5),
    messageCount: 3,
    category: "Re-evaluation",
    urgency: "Critical",
    actionNeeded: true,
    deadline: inDays(1),
    aiExplanation:
      "Student disputes a graded answer and requests re-evaluation before the Friday departmental deadline.",
    isRead: false,
    needsFollowUp: false,
    correctedCategory: null,
    messages: [
      {
        sender: "Nafis Iqbal",
        isFaculty: false,
        sentAt: h(52),
        body: "Respected Ma'am, I scored 11/20 in the CSE 3201 midterm. I think question 4 (b) was not evaluated. Could you please review my script?",
      },
      {
        sender: FACULTY,
        isFaculty: true,
        sentAt: h(30),
        body: "I will pull your script from the exam office and check. Please share your registration number.",
      },
      {
        sender: "Nafis Iqbal",
        isFaculty: false,
        sentAt: h(5),
        body: "Registration 19203045. The controller's office told me re-evaluation forms must be signed by Friday, so I wanted to remind you. Thank you.",
      },
    ],
  },
  {
    id: "t-002",
    subject: "Department meeting — curriculum revision (attendance confirmation)",
    participants: ["Prof. Kamal Hossain", "Department Faculty"],
    lastMessagePreview: "Please confirm your attendance for Monday's revision meeting.",
    lastMessageAt: h(74),
    messageCount: 1,
    category: "Meeting",
    urgency: "Critical",
    actionNeeded: true,
    deadline: inDays(2),
    aiExplanation:
      "Chair is waiting on your attendance confirmation; the invite has been unanswered for three days.",
    isRead: false,
    needsFollowUp: true,
    correctedCategory: null,
    messages: [
      {
        sender: "Prof. Kamal Hossain",
        isFaculty: false,
        sentAt: h(74),
        body: "Dear colleagues, the curriculum revision meeting is scheduled for Monday 10:00 AM in Room 402. Kindly confirm attendance by Sunday so quorum can be verified.",
      },
    ],
  },
  {
    id: "t-003",
    subject: "Final exam question paper moderation — CSE 4105",
    participants: ["Exam Committee", "Dr. Sadia Karim", FACULTY],
    lastMessagePreview: "Moderation sheet needs your sign-off before Thursday.",
    lastMessageAt: h(20),
    messageCount: 4,
    category: "Examination",
    urgency: "High",
    actionNeeded: true,
    deadline: inDays(3),
    aiExplanation:
      "Committee cannot finalise the paper until you sign the moderation sheet before Thursday.",
    isRead: true,
    needsFollowUp: false,
    correctedCategory: null,
    messages: [
      {
        sender: "Exam Committee",
        isFaculty: false,
        sentAt: h(96),
        body: "Attached is the draft question paper for CSE 4105 along with the moderation sheet.",
      },
      {
        sender: FACULTY,
        isFaculty: true,
        sentAt: h(70),
        body: "Received. I have comments on Q2 and Q5 — marks distribution looks uneven.",
      },
      {
        sender: "Dr. Sadia Karim",
        isFaculty: false,
        sentAt: h(44),
        body: "I have adjusted Q2 to 8 marks and split Q5 into two parts. Please review.",
      },
      {
        sender: "Exam Committee",
        isFaculty: false,
        sentAt: h(20),
        body: "Kindly return the signed moderation sheet by Thursday noon so printing can start.",
      },
    ],
  },
  {
    id: "t-004",
    subject: "Student unable to sit for retake — medical documents attached",
    participants: ["Tanzim Ahmed", "Registrar Office"],
    lastMessagePreview: "Hospital discharge papers attached as advised.",
    lastMessageAt: h(9),
    messageCount: 2,
    category: "Student Issue",
    urgency: "High",
    actionNeeded: true,
    deadline: inDays(4),
    aiExplanation:
      "Student submitted medical proof and needs your recommendation for a special retake.",
    isRead: false,
    needsFollowUp: false,
    correctedCategory: null,
    messages: [
      {
        sender: "Tanzim Ahmed",
        isFaculty: false,
        sentAt: h(30),
        body: "Ma'am, I was hospitalised during the retake week. May I request a special examination?",
      },
      {
        sender: "Tanzim Ahmed",
        isFaculty: false,
        sentAt: h(9),
        body: "As advised by the registrar's office, I am attaching the discharge summary and doctor's certificate.",
      },
    ],
  },
  {
    id: "t-005",
    subject: "Room change for CSE 2103 lab section B",
    participants: ["Academic Scheduling", FACULTY],
    lastMessagePreview: "Lab 3 is under maintenance; section B moved to Lab 5 from next week.",
    lastMessageAt: h(15),
    messageCount: 2,
    category: "Class/Schedule",
    urgency: "Medium",
    actionNeeded: true,
    deadline: inDays(5),
    aiExplanation:
      "Scheduling office needs you to acknowledge the lab room change before next week's session.",
    isRead: true,
    needsFollowUp: false,
    correctedCategory: null,
    messages: [
      {
        sender: "Academic Scheduling",
        isFaculty: false,
        sentAt: h(40),
        body: "Lab 3 will be closed for equipment maintenance for two weeks starting Monday.",
      },
      {
        sender: "Academic Scheduling",
        isFaculty: false,
        sentAt: h(15),
        body: "Section B of CSE 2103 has been provisionally moved to Lab 5, same time slot. Please acknowledge.",
      },
    ],
  },
  {
    id: "t-006",
    subject: "Thesis supervision meeting — reschedule request",
    participants: ["Rifat Chowdhury"],
    lastMessagePreview: "Could we move our Tuesday slot to Wednesday afternoon?",
    lastMessageAt: h(64),
    messageCount: 1,
    category: "Meeting",
    urgency: "Medium",
    actionNeeded: true,
    deadline: null,
    aiExplanation:
      "Thesis student asked to reschedule and has had no reply for over two days.",
    isRead: false,
    needsFollowUp: true,
    correctedCategory: null,
    messages: [
      {
        sender: "Rifat Chowdhury",
        isFaculty: false,
        sentAt: h(64),
        body: "Ma'am, I have a viva clash on Tuesday. Could we move our supervision meeting to Wednesday after 2 PM?",
      },
    ],
  },
  {
    id: "t-007",
    subject: "Grade submission portal closes tonight — 2 courses pending",
    participants: ["Controller of Examinations"],
    lastMessagePreview: "CSE 3201 and CSE 4105 grades are still marked incomplete.",
    lastMessageAt: h(3),
    messageCount: 1,
    category: "Examination",
    urgency: "Critical",
    actionNeeded: true,
    deadline: inDays(0),
    aiExplanation:
      "Grade portal closes tonight and two of your courses are still incomplete.",
    isRead: false,
    needsFollowUp: false,
    correctedCategory: null,
    messages: [
      {
        sender: "Controller of Examinations",
        isFaculty: false,
        sentAt: h(3),
        body: "This is a final reminder: the grade submission portal locks at 11:59 PM today. Courses still pending from your account: CSE 3201, CSE 4105.",
      },
    ],
  },
  {
    id: "t-008",
    subject: "Re-evaluation outcome sheet — 4 pending signatures",
    participants: ["Exam Section", "Dr. Farhan Alam"],
    lastMessagePreview: "Four re-evaluation outcomes await your counter-signature.",
    lastMessageAt: h(120),
    messageCount: 2,
    category: "Re-evaluation",
    urgency: "High",
    actionNeeded: true,
    deadline: inDays(6),
    aiExplanation:
      "Four student re-evaluation results are stalled waiting on your signature for five days.",
    isRead: false,
    needsFollowUp: true,
    correctedCategory: null,
    messages: [
      {
        sender: "Exam Section",
        isFaculty: false,
        sentAt: h(150),
        body: "Please find the re-evaluation outcome sheet for the Spring semester attached.",
      },
      {
        sender: "Dr. Farhan Alam",
        isFaculty: false,
        sentAt: h(120),
        body: "I have signed as second examiner. Four entries still need your counter-signature before results can be published.",
      },
    ],
  },
  {
    id: "t-009",
    subject: "Plagiarism concern in CSE 3103 term project",
    participants: ["Teaching Assistant — Mahin", FACULTY],
    lastMessagePreview: "Two submissions show 71% similarity with each other.",
    lastMessageAt: h(27),
    messageCount: 3,
    category: "Student Issue",
    urgency: "High",
    actionNeeded: true,
    deadline: inDays(7),
    aiExplanation:
      "Suspected plagiarism case needs your decision before grades are finalised.",
    isRead: true,
    needsFollowUp: false,
    correctedCategory: null,
    messages: [
      {
        sender: "Teaching Assistant — Mahin",
        isFaculty: false,
        sentAt: h(56),
        body: "Ma'am, the similarity checker flagged two term project reports at 71%.",
      },
      {
        sender: FACULTY,
        isFaculty: true,
        sentAt: h(40),
        body: "Please share the report IDs and the similarity summary.",
      },
      {
        sender: "Teaching Assistant — Mahin",
        isFaculty: false,
        sentAt: h(27),
        body: "Sent via the LMS. Both students say they worked in the same lab group. Should we call them for a hearing?",
      },
    ],
  },
  {
    id: "t-010",
    subject: "Makeup class scheduling for missed Friday lectures",
    participants: ["Class Representative — Sumaiya"],
    lastMessagePreview: "Students prefer Saturday 9 AM for the makeup class.",
    lastMessageAt: h(11),
    messageCount: 2,
    category: "Class/Schedule",
    urgency: "Medium",
    actionNeeded: true,
    deadline: inDays(2),
    aiExplanation:
      "Class representative is waiting on you to confirm the makeup class slot.",
    isRead: true,
    needsFollowUp: false,
    correctedCategory: null,
    messages: [
      {
        sender: "Class Representative — Sumaiya",
        isFaculty: false,
        sentAt: h(36),
        body: "Ma'am, we missed two Friday lectures due to the public holiday.",
      },
      {
        sender: "Class Representative — Sumaiya",
        isFaculty: false,
        sentAt: h(11),
        body: "We polled the class — 34 of 40 students prefer Saturday 9 AM. Shall we book Room 301?",
      },
    ],
  },
  {
    id: "t-011",
    subject: "Admission committee — shortlisting criteria discussion",
    participants: ["Prof. Kamal Hossain", "Admission Committee"],
    lastMessagePreview: "Draft criteria attached for comments before the next sitting.",
    lastMessageAt: h(48),
    messageCount: 2,
    category: "Committee/Admin",
    urgency: "Medium",
    actionNeeded: true,
    deadline: inDays(8),
    aiExplanation:
      "Committee requested written comments on the shortlisting criteria before the next sitting.",
    isRead: true,
    needsFollowUp: false,
    correctedCategory: null,
    messages: [
      {
        sender: "Admission Committee",
        isFaculty: false,
        sentAt: h(70),
        body: "Draft shortlisting criteria for the upcoming admission cycle is attached.",
      },
      {
        sender: "Prof. Kamal Hossain",
        isFaculty: false,
        sentAt: h(48),
        body: "Colleagues, please send your comments within a week so we can finalise at the next sitting.",
      },
    ],
  },
  {
    id: "t-012",
    subject: "Student requesting recommendation letter for MS applications",
    participants: ["Ishrat Jahan"],
    lastMessagePreview: "Deadline for the first university is the 20th.",
    lastMessageAt: h(90),
    messageCount: 2,
    category: "Student Issue",
    urgency: "Medium",
    actionNeeded: true,
    deadline: inDays(9),
    aiExplanation:
      "Former student needs a recommendation letter and has waited nearly four days for a reply.",
    isRead: false,
    needsFollowUp: true,
    correctedCategory: null,
    messages: [
      {
        sender: "Ishrat Jahan",
        isFaculty: false,
        sentAt: h(110),
        body: "Ma'am, I am applying for MS programs this fall and would be grateful for a recommendation letter.",
      },
      {
        sender: "Ishrat Jahan",
        isFaculty: false,
        sentAt: h(90),
        body: "I have attached my CV and statement of purpose. The first deadline is the 20th.",
      },
    ],
  },
  {
    id: "t-013",
    subject: "Invigilation duty roster — Fall final examinations",
    participants: ["Exam Section"],
    lastMessagePreview: "You are assigned three morning slots; conflicts by Sunday.",
    lastMessageAt: h(33),
    messageCount: 1,
    category: "Examination",
    urgency: "Medium",
    actionNeeded: true,
    deadline: inDays(3),
    aiExplanation:
      "You must report scheduling conflicts in the invigilation roster by Sunday.",
    isRead: true,
    needsFollowUp: false,
    correctedCategory: null,
    messages: [
      {
        sender: "Exam Section",
        isFaculty: false,
        sentAt: h(33),
        body: "The Fall invigilation roster is published. You have three morning slots. Report conflicts by Sunday, otherwise the roster is treated as accepted.",
      },
    ],
  },
  {
    id: "t-014",
    subject: "Board of studies meeting minutes — approval needed",
    participants: ["Department Office", "Board Members"],
    lastMessagePreview: "Minutes of the 42nd meeting circulated for approval.",
    lastMessageAt: h(58),
    messageCount: 1,
    category: "Committee/Admin",
    urgency: "Low",
    actionNeeded: true,
    deadline: inDays(10),
    aiExplanation:
      "Routine approval request for circulated minutes; no substantive action expected.",
    isRead: true,
    needsFollowUp: false,
    correctedCategory: null,
    messages: [
      {
        sender: "Department Office",
        isFaculty: false,
        sentAt: h(58),
        body: "Minutes of the 42nd Board of Studies meeting are attached. Please reply with approval or corrections within ten days.",
      },
    ],
  },
  {
    id: "t-015",
    subject: "Lab equipment purchase requisition — signature pending",
    participants: ["Lab Coordinator", "Accounts"],
    lastMessagePreview: "Requisition 2291 waiting on the course coordinator's sign-off.",
    lastMessageAt: h(102),
    messageCount: 2,
    category: "Committee/Admin",
    urgency: "Medium",
    actionNeeded: true,
    deadline: inDays(4),
    aiExplanation:
      "Purchase requisition has been stuck on your sign-off for over four days.",
    isRead: false,
    needsFollowUp: true,
    correctedCategory: null,
    messages: [
      {
        sender: "Lab Coordinator",
        isFaculty: false,
        sentAt: h(130),
        body: "Requisition 2291 covers 12 oscilloscope probes for the digital lab.",
      },
      {
        sender: "Accounts",
        isFaculty: false,
        sentAt: h(102),
        body: "We cannot process requisition 2291 without the course coordinator's signature. Kindly sign at your earliest convenience.",
      },
    ],
  },
  {
    id: "t-016",
    subject: "Student appealing attendance shortfall — CSE 2103",
    participants: ["Arafat Karim"],
    lastMessagePreview: "I was on university sports duty for four of those classes.",
    lastMessageAt: h(22),
    messageCount: 3,
    category: "Student Issue",
    urgency: "High",
    actionNeeded: true,
    deadline: inDays(2),
    aiExplanation:
      "Student risks exam ineligibility and is appealing an attendance shortfall before the cutoff.",
    isRead: false,
    needsFollowUp: false,
    correctedCategory: null,
    messages: [
      {
        sender: "Arafat Karim",
        isFaculty: false,
        sentAt: h(60),
        body: "Sir/Ma'am, the LMS shows my attendance at 68%, which blocks me from the final exam.",
      },
      {
        sender: FACULTY,
        isFaculty: true,
        sentAt: h(44),
        body: "Do you have documentation for the classes you missed?",
      },
      {
        sender: "Arafat Karim",
        isFaculty: false,
        sentAt: h(22),
        body: "Yes — I represented the university in the inter-university football tournament for four of those classes. The sports office letter is attached.",
      },
    ],
  },
  {
    id: "t-017",
    subject: "Guest lecture slot — industry speaker availability",
    participants: ["Career Services", FACULTY],
    lastMessagePreview: "Speaker is available on the 18th or the 25th.",
    lastMessageAt: h(19),
    messageCount: 2,
    category: "Class/Schedule",
    urgency: "Low",
    actionNeeded: true,
    deadline: inDays(12),
    aiExplanation:
      "Optional guest lecture scheduling; flexible dates and no hard deadline pressure.",
    isRead: true,
    needsFollowUp: false,
    correctedCategory: null,
    messages: [
      {
        sender: "Career Services",
        isFaculty: false,
        sentAt: h(40),
        body: "A senior engineer from a partner firm has offered a guest lecture for your software engineering course.",
      },
      {
        sender: "Career Services",
        isFaculty: false,
        sentAt: h(19),
        body: "He is available on the 18th or the 25th. Let us know which fits your class schedule.",
      },
    ],
  },
  {
    id: "t-018",
    subject: "Second examiner needed for two re-evaluation scripts",
    participants: ["Dr. Sadia Karim"],
    lastMessagePreview: "Can you act as second examiner for two scripts this week?",
    lastMessageAt: h(13),
    messageCount: 1,
    category: "Re-evaluation",
    urgency: "Medium",
    actionNeeded: true,
    deadline: inDays(5),
    aiExplanation:
      "Colleague is asking you to serve as second examiner for two re-evaluation scripts.",
    isRead: false,
    needsFollowUp: false,
    correctedCategory: null,
    messages: [
      {
        sender: "Dr. Sadia Karim",
        isFaculty: false,
        sentAt: h(13),
        body: "Two students of CSE 3105 applied for re-evaluation. Departmental rules need a second examiner from outside the course team — would you be able to take these two scripts this week?",
      },
    ],
  },
  {
    id: "t-019",
    subject: "Faculty seminar — presenting slot confirmation",
    participants: ["Research Office"],
    lastMessagePreview: "Your slot is tentatively the first Wednesday of next month.",
    lastMessageAt: h(80),
    messageCount: 1,
    category: "Meeting",
    urgency: "Low",
    actionNeeded: false,
    deadline: null,
    aiExplanation:
      "Informational notice about a tentative seminar slot; confirmation requested but not urgent.",
    isRead: true,
    needsFollowUp: false,
    correctedCategory: null,
    messages: [
      {
        sender: "Research Office",
        isFaculty: false,
        sentAt: h(80),
        body: "Your faculty seminar presentation is tentatively scheduled for the first Wednesday of next month. Title and abstract can follow later.",
      },
    ],
  },
  {
    id: "t-020",
    subject: "University Weekly — campus news and notices",
    participants: ["University Communications"],
    lastMessagePreview: "Highlights: new library hours, sports week, alumni fund drive.",
    lastMessageAt: h(26),
    messageCount: 1,
    category: "Other",
    urgency: "Low",
    actionNeeded: false,
    deadline: null,
    aiExplanation:
      "Broadcast newsletter with no request directed at you — filtered out of the priority view.",
    isRead: true,
    needsFollowUp: false,
    correctedCategory: null,
    messages: [
      {
        sender: "University Communications",
        isFaculty: false,
        sentAt: h(26),
        body: "In this issue: extended library hours during finals, sports week schedule, and the alumni fund drive update.",
      },
    ],
  },
  {
    id: "t-021",
    subject: "IT Security: scheduled password rotation this weekend",
    participants: ["IT Helpdesk"],
    lastMessagePreview: "All staff accounts will require a password reset on Saturday.",
    lastMessageAt: h(35),
    messageCount: 1,
    category: "Other",
    urgency: "Low",
    actionNeeded: false,
    deadline: null,
    aiExplanation:
      "Automated IT advisory sent campus-wide; not academic work and needs no reply.",
    isRead: false,
    needsFollowUp: false,
    correctedCategory: null,
    messages: [
      {
        sender: "IT Helpdesk",
        isFaculty: false,
        sentAt: h(35),
        body: "As part of routine security maintenance, all staff accounts will prompt for a new password after Saturday 2 AM. No action is needed before then.",
      },
    ],
  },
  {
    id: "t-022",
    subject: "Call for papers — International Conference on Computing Systems",
    participants: ["ICCS Organising Committee"],
    lastMessagePreview: "Abstract submissions open until the end of the month.",
    lastMessageAt: h(62),
    messageCount: 1,
    category: "Other",
    urgency: "Low",
    actionNeeded: false,
    deadline: null,
    aiExplanation:
      "Unsolicited conference invitation; opportunity rather than an obligation, so kept out of priorities.",
    isRead: true,
    needsFollowUp: false,
    correctedCategory: null,
    messages: [
      {
        sender: "ICCS Organising Committee",
        isFaculty: false,
        sentAt: h(62),
        body: "We invite submissions to ICCS across systems, networking, and applied machine learning tracks. Abstracts are open until month end.",
      },
    ],
  },
  {
    id: "t-023",
    subject: "Vendor introduction — laboratory software licences",
    participants: ["Sales — LabSoft Ltd."],
    lastMessagePreview: "We would love 15 minutes to demo our simulation suite.",
    lastMessageAt: h(46),
    messageCount: 1,
    category: "Other",
    urgency: "Low",
    actionNeeded: false,
    deadline: null,
    aiExplanation:
      "Cold sales outreach with no academic relevance; safely deprioritised.",
    isRead: true,
    needsFollowUp: false,
    correctedCategory: null,
    messages: [
      {
        sender: "Sales — LabSoft Ltd.",
        isFaculty: false,
        sentAt: h(46),
        body: "Hello Professor, our simulation suite is used by several engineering departments. Could we schedule a 15-minute demo?",
      },
    ],
  },
  {
    id: "t-024",
    subject: "Course outline upload reminder — LMS deadline",
    participants: ["Quality Assurance Cell"],
    lastMessagePreview: "Two of your three course outlines are not yet uploaded.",
    lastMessageAt: h(7),
    messageCount: 1,
    category: "Class/Schedule",
    urgency: "High",
    actionNeeded: true,
    deadline: inDays(2),
    aiExplanation:
      "Accreditation cell needs two missing course outlines uploaded within two days.",
    isRead: false,
    needsFollowUp: false,
    correctedCategory: null,
    messages: [
      {
        sender: "Quality Assurance Cell",
        isFaculty: false,
        sentAt: h(7),
        body: "For the accreditation audit, all course outlines must be on the LMS. Records show two of your three courses are pending.",
      },
    ],
  },
  {
    id: "t-025",
    subject: "Student counselling referral — academic probation case",
    participants: ["Student Affairs", FACULTY],
    lastMessagePreview: "Advisor notes requested before the counselling session.",
    lastMessageAt: h(84),
    messageCount: 2,
    category: "Student Issue",
    urgency: "Medium",
    actionNeeded: true,
    deadline: inDays(3),
    aiExplanation:
      "Student affairs is waiting on your advisor notes and has had no reply for three days.",
    isRead: false,
    needsFollowUp: true,
    correctedCategory: null,
    messages: [
      {
        sender: "Student Affairs",
        isFaculty: false,
        sentAt: h(100),
        body: "One of your advisees has been placed on academic probation and is scheduled for counselling.",
      },
      {
        sender: "Student Affairs",
        isFaculty: false,
        sentAt: h(84),
        body: "Could you share your advisor notes before the session so the counsellor has context?",
      },
    ],
  },
];

export const FACULTY_USER = {
  name: FACULTY,
  role: "Associate Professor, Computer Science & Engineering",
};
