import { IngestionProvider, RawThread } from "./IngestionProvider.js";

export class MockIngestionProvider implements IngestionProvider {
  name = "mock";

  async fetchThreads(_userId: string): Promise<RawThread[]> {
    const now = new Date();
    const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600 * 1000);
    const daysAgo = (d: number) => new Date(now.getTime() - d * 24 * 3600 * 1000);
    const daysAhead = (d: number) => new Date(now.getTime() + d * 24 * 3600 * 1000);

    const mockThreads: RawThread[] = [
      {
        externalThreadId: "th-mock-001",
        subject: "URGENT: Re-evaluation Request - CS301 Midterm Grade",
        participants: ["David Zhao <dzhao@student.univ.edu>", "Dr. Eleanor Vance <evance@univ.edu>"],
        lastMessageAt: hoursAgo(52),
        messages: [
          {
            sender: "David Zhao <dzhao@student.univ.edu>",
            senderIsFaculty: false,
            sentAt: hoursAgo(54),
            body: "Dear Professor Vance, I believe Question 4 on my CS301 midterm was scored incorrectly based on the rubric. The registrar deadline for grade appeals is tomorrow at 5 PM. Could you please review my submission?",
          },
          {
            sender: "David Zhao <dzhao@student.univ.edu>",
            senderIsFaculty: false,
            sentAt: hoursAgo(52),
            body: "Following up with the attached scan of my exam paper. Thank you for your time.",
          },
        ],
        mockCategory: "Re-evaluation",
        mockUrgency: "Critical",
        mockActionNeeded: true,
        mockDeadline: daysAhead(1),
        mockAiExplanation: "Student disputes midterm grade with formal appeal deadline tomorrow at 5 PM.",
        mockIsRead: false,
      },
      {
        externalThreadId: "th-mock-002",
        subject: "Emergency Department Chair Meeting: Accreditation Audit",
        participants: ["Prof. Arthur Pendelton <chair.cs@univ.edu>", "Dr. Eleanor Vance <evance@univ.edu>"],
        lastMessageAt: hoursAgo(72),
        messages: [
          {
            sender: "Prof. Arthur Pendelton <chair.cs@univ.edu>",
            senderIsFaculty: false,
            sentAt: hoursAgo(72),
            body: "Eleanor, the ABET accreditation panel requested our revised course outcomes by this Thursday. Are you available for a 30-min sync tomorrow morning at 9:30 AM? Please confirm.",
          },
        ],
        mockCategory: "Meeting",
        mockUrgency: "Critical",
        mockActionNeeded: true,
        mockDeadline: daysAhead(2),
        mockAiExplanation: "Department chair requested urgent confirmation for accreditation sync; unanswered for 3 days.",
        mockIsRead: false,
      },
      {
        externalThreadId: "th-mock-003",
        subject: "Final Exam Paper Submission Deadline - CS410",
        participants: ["Exam Committee <exam-office@univ.edu>", "Dr. Eleanor Vance <evance@univ.edu>"],
        lastMessageAt: hoursAgo(30),
        messages: [
          {
            sender: "Exam Committee <exam-office@univ.edu>",
            senderIsFaculty: false,
            sentAt: hoursAgo(30),
            body: "Reminder: All final exam master copies and answer rubrics for CS410 must be uploaded to the portal by Friday noon for secure printing.",
          },
        ],
        mockCategory: "Examination",
        mockUrgency: "High",
        mockActionNeeded: true,
        mockDeadline: daysAhead(3),
        mockAiExplanation: "Exam office requires finalized master exam paper and rubric uploaded by Friday noon.",
        mockIsRead: true,
      },
      {
        externalThreadId: "th-mock-004",
        subject: "Room Conflict: CS202 Lab Relocation for Weeks 8-10",
        participants: ["Academic Scheduling <scheduling@univ.edu>", "Dr. Eleanor Vance <evance@univ.edu>"],
        lastMessageAt: hoursAgo(60),
        messages: [
          {
            sender: "Academic Scheduling <scheduling@univ.edu>",
            senderIsFaculty: false,
            sentAt: hoursAgo(60),
            body: "Due to HVAC maintenance in Turing Hall Lab B, CS202 Section 3 will need to move to Lovelace 104 or switch to a hybrid slot. Please let us know your preference before end of day.",
          },
        ],
        mockCategory: "Class/Schedule",
        mockUrgency: "High",
        mockActionNeeded: true,
        mockDeadline: daysAhead(1),
        mockAiExplanation: "Lab room maintenance forces section relocation; pending faculty room preference decision.",
        mockIsRead: false,
      },
      {
        externalThreadId: "th-mock-005",
        subject: "Student Support: Mental Health Medical Leave Inquiry (Sarah Lin)",
        participants: ["Dean of Students Office <studentaffairs@univ.edu>", "Dr. Eleanor Vance <evance@univ.edu>"],
        lastMessageAt: hoursAgo(24),
        messages: [
          {
            sender: "Dean of Students Office <studentaffairs@univ.edu>",
            senderIsFaculty: false,
            sentAt: hoursAgo(24),
            body: "We are coordinating an excused medical leave accommodation for Sarah Lin (ID: 88291). Please provide her current attendance and assignment standing as of week 6.",
          },
        ],
        mockCategory: "Student Issue",
        mockUrgency: "High",
        mockActionNeeded: true,
        mockDeadline: daysAhead(2),
        mockAiExplanation: "Dean of Students requesting student academic standing for formal medical accommodation.",
        mockIsRead: false,
      },
      {
        externalThreadId: "th-mock-006",
        subject: "Curriculum Committee: Proposed AI Ethics Elective Syllabus Review",
        participants: ["Dr. Maya Lin <mlin@univ.edu>", "Dr. Eleanor Vance <evance@univ.edu>"],
        lastMessageAt: daysAgo(3),
        messages: [
          {
            sender: "Dr. Maya Lin <mlin@univ.edu>",
            senderIsFaculty: false,
            sentAt: daysAgo(4),
            body: "Hi Eleanor, attached is the 14-week draft for the new AI Ethics course. Could you review modules 4-6 on algorithmic fairness and send your remarks?",
          },
          {
            sender: "Dr. Eleanor Vance <evance@univ.edu>",
            senderIsFaculty: true,
            sentAt: daysAgo(3),
            body: "Thanks Maya! I will take a close look this week and get notes over to the committee.",
          },
        ],
        mockCategory: "Committee/Admin",
        mockUrgency: "Medium",
        mockActionNeeded: false,
        mockDeadline: daysAhead(5),
        mockAiExplanation: "Curriculum committee syllabus review; faculty already acknowledged and replied.",
        mockIsRead: true,
      },
      {
        externalThreadId: "th-mock-007",
        subject: "Midterm Regrade: Question 2 Partial Credit",
        participants: ["Marcus Thorne <mthorne@student.univ.edu>", "Dr. Eleanor Vance <evance@univ.edu>"],
        lastMessageAt: hoursAgo(80),
        messages: [
          {
            sender: "Marcus Thorne <mthorne@student.univ.edu>",
            senderIsFaculty: false,
            sentAt: hoursAgo(80),
            body: "Professor Vance, I wrote the auxiliary lemmas on page 4 but the grader noted incomplete proof. Could you look at the scanned page?",
          },
        ],
        mockCategory: "Re-evaluation",
        mockUrgency: "High",
        mockActionNeeded: true,
        mockDeadline: daysAhead(2),
        mockAiExplanation: "Student questioning partial credit deduction; unanswered for over 3 days.",
        mockIsRead: false,
      },
      {
        externalThreadId: "th-mock-008",
        subject: "Faculty Search Committee: Candidate Interview Scheduling",
        participants: ["Hiring Committee Coordinator <search@univ.edu>", "Dr. Eleanor Vance <evance@univ.edu>"],
        lastMessageAt: hoursAgo(18),
        messages: [
          {
            sender: "Hiring Committee Coordinator <search@univ.edu>",
            senderIsFaculty: false,
            sentAt: hoursAgo(18),
            body: "Dr. Sophia Ramos will be on campus next Tuesday. Please indicate your availability for a 45-minute 1-on-1 interview slot between 1:00 PM and 4:30 PM.",
          },
        ],
        mockCategory: "Committee/Admin",
        mockUrgency: "Medium",
        mockActionNeeded: true,
        mockDeadline: daysAhead(4),
        mockAiExplanation: "Candidate campus interview slot selection needed for faculty hiring committee.",
        mockIsRead: true,
      },
      {
        externalThreadId: "th-mock-009",
        subject: "Accommodation Letter: Extended Testing Time (CS301)",
        participants: ["Disability Resource Center <drc@univ.edu>", "Dr. Eleanor Vance <evance@univ.edu>"],
        lastMessageAt: hoursAgo(12),
        messages: [
          {
            sender: "Disability Resource Center <drc@univ.edu>",
            senderIsFaculty: false,
            sentAt: hoursAgo(12),
            body: "Official accommodation notice: Liam O'Connor is approved for 1.5x testing time and a reduced-distraction environment for all remaining semester examinations.",
          },
        ],
        mockCategory: "Student Issue",
        mockUrgency: "Medium",
        mockActionNeeded: false,
        mockDeadline: null,
        mockAiExplanation: "Official DRC testing accommodation letter recorded for midterm and final exam logistics.",
        mockIsRead: true,
      },
      {
        externalThreadId: "th-mock-010",
        subject: "Guest Lecture Confirmation - Dr. Chen on Quantum Computing",
        participants: ["Dr. Wei Chen <wchen@mit.edu>", "Dr. Eleanor Vance <evance@univ.edu>"],
        lastMessageAt: daysAgo(2),
        messages: [
          {
            sender: "Dr. Eleanor Vance <evance@univ.edu>",
            senderIsFaculty: true,
            sentAt: daysAgo(3),
            body: "Hi Wei, could you confirm your slide deck title and whether you need Zoom webinar setup?",
          },
          {
            sender: "Dr. Wei Chen <wchen@mit.edu>",
            senderIsFaculty: false,
            sentAt: daysAgo(2),
            body: "Confirmed! Title is 'Near-term Quantum Algorithms'. Regular Zoom with screen share is perfect.",
          },
        ],
        mockCategory: "Meeting",
        mockUrgency: "Low",
        mockActionNeeded: false,
        mockDeadline: null,
        mockAiExplanation: "Guest speaker confirmed talk details and audio-visual requirements.",
        mockIsRead: true,
      },
      {
        externalThreadId: "th-mock-011",
        subject: "Teaching Assistant Hours Timesheet Approval (CS301)",
        participants: ["Payroll & TA Office <ta-payroll@univ.edu>", "Dr. Eleanor Vance <evance@univ.edu>"],
        lastMessageAt: hoursAgo(50),
        messages: [
          {
            sender: "Payroll & TA Office <ta-payroll@univ.edu>",
            senderIsFaculty: false,
            sentAt: hoursAgo(50),
            body: "Please approve the bi-weekly logged hours for TA Alex Rivera (28.5 hrs) in the staff portal before the payroll cutoff this Wednesday.",
          },
        ],
        mockCategory: "Committee/Admin",
        mockUrgency: "High",
        mockActionNeeded: true,
        mockDeadline: daysAhead(1),
        mockAiExplanation: "TA timesheet approval required before bi-weekly payroll cutoff deadline.",
        mockIsRead: false,
      },
      {
        externalThreadId: "th-mock-012",
        subject: "Academic Integrity Inquiry: CS202 Homework 3 Similarities",
        participants: ["TA Alex Rivera <arivera@univ.edu>", "Dr. Eleanor Vance <evance@univ.edu>"],
        lastMessageAt: hoursAgo(16),
        messages: [
          {
            sender: "TA Alex Rivera <arivera@univ.edu>",
            senderIsFaculty: false,
            sentAt: hoursAgo(16),
            body: "Moss similarity report flagged two student submissions with 94% code overlap on the binary search tree assignment. Attached are the side-by-side diffs for your review.",
          },
        ],
        mockCategory: "Student Issue",
        mockUrgency: "High",
        mockActionNeeded: true,
        mockDeadline: daysAhead(3),
        mockAiExplanation: "TA flagged high Moss code similarity on CS202 homework requiring faculty academic integrity determination.",
        mockIsRead: false,
      },
      {
        externalThreadId: "th-mock-013",
        subject: "Final Exam Proctoring Schedule Sign-up",
        participants: ["Dean of Faculty Office <deanfac@univ.edu>", "Dr. Eleanor Vance <evance@univ.edu>"],
        lastMessageAt: daysAgo(4),
        messages: [
          {
            sender: "Dean of Faculty Office <deanfac@univ.edu>",
            senderIsFaculty: false,
            sentAt: daysAgo(4),
            body: "All full-time faculty members must sign up for at least two proctoring slots during exam week (Dec 14-20). 12 slots remain unstaffed.",
          },
        ],
        mockCategory: "Examination",
        mockUrgency: "Medium",
        mockActionNeeded: true,
        mockDeadline: daysAhead(7),
        mockAiExplanation: "Faculty proctoring duty sign-up for upcoming semester exam week.",
        mockIsRead: true,
      },
      {
        externalThreadId: "th-mock-014",
        subject: "Classroom Microphone Replacement Completed - Hall 101",
        participants: ["Campus AV Support <avsupport@univ.edu>", "Dr. Eleanor Vance <evance@univ.edu>"],
        lastMessageAt: daysAgo(1),
        messages: [
          {
            sender: "Campus AV Support <avsupport@univ.edu>",
            senderIsFaculty: false,
            sentAt: daysAgo(1),
            body: "Ticket #4491: The wireless lapel mic in Hall 101 has been replaced and verified with the transmitter. Case closed.",
          },
        ],
        mockCategory: "Class/Schedule",
        mockUrgency: "Low",
        mockActionNeeded: false,
        mockDeadline: null,
        mockAiExplanation: "AV ticket resolved: lapel mic replaced in lecture hall.",
        mockIsRead: true,
      },
      {
        externalThreadId: "th-mock-015",
        subject: "Office Hours Reschedule Notice",
        participants: ["Priya Patel <ppatel@student.univ.edu>", "Dr. Eleanor Vance <evance@univ.edu>"],
        lastMessageAt: hoursAgo(28),
        messages: [
          {
            sender: "Priya Patel <ppatel@student.univ.edu>",
            senderIsFaculty: false,
            sentAt: hoursAgo(28),
            body: "Dear Dr. Vance, I have a lab conflict during your regular Thursday 2 PM office hours. Would it be possible to meet for 10 minutes on Friday morning instead?",
          },
        ],
        mockCategory: "Meeting",
        mockUrgency: "Medium",
        mockActionNeeded: true,
        mockDeadline: daysAhead(2),
        mockAiExplanation: "Student requesting alternative office hours appointment due to lab conflict.",
        mockIsRead: false,
      },
      {
        externalThreadId: "th-mock-016",
        subject: "Textbook Desk Copies Order for Spring Semester",
        participants: ["University Bookstore <bookstore@univ.edu>", "Dr. Eleanor Vance <evance@univ.edu>"],
        lastMessageAt: daysAgo(5),
        messages: [
          {
            sender: "University Bookstore <bookstore@univ.edu>",
            senderIsFaculty: false,
            sentAt: daysAgo(5),
            body: "Faculty ordering portal is open for Spring book adoptions. If you require complimentary desk copies from Pearson or Wiley, place orders by end of month.",
          },
        ],
        mockCategory: "Class/Schedule",
        mockUrgency: "Low",
        mockActionNeeded: false,
        mockDeadline: daysAhead(14),
        mockAiExplanation: "Optional textbook desk copy adoption portal announcement.",
        mockIsRead: true,
      },
      {
        externalThreadId: "th-mock-017",
        subject: "Incomplete Grade Resolution Contract: Robert Jenkins",
        participants: ["Registrar Office <registrar@univ.edu>", "Dr. Eleanor Vance <evance@univ.edu>"],
        lastMessageAt: hoursAgo(96),
        messages: [
          {
            sender: "Registrar Office <registrar@univ.edu>",
            senderIsFaculty: false,
            sentAt: hoursAgo(96),
            body: "Robert Jenkins completed his overdue project for Fall CS301. Please submit the final change-of-grade form before the default F conversion date.",
          },
        ],
        mockCategory: "Re-evaluation",
        mockUrgency: "High",
        mockActionNeeded: true,
        mockDeadline: daysAhead(2),
        mockAiExplanation: "Registrar pending incomplete grade conversion form before default failing grade triggers; 4 days unanswered.",
        mockIsRead: false,
      },
      {
        externalThreadId: "th-mock-018",
        subject: "Spring Graduate Admissions Committee: Portfolio Review Round 1",
        participants: ["Grad Admissions <gradchair@univ.edu>", "Dr. Eleanor Vance <evance@univ.edu>"],
        lastMessageAt: daysAgo(2),
        messages: [
          {
            sender: "Grad Admissions <gradchair@univ.edu>",
            senderIsFaculty: false,
            sentAt: daysAgo(2),
            body: "25 PhD applicant folders have been assigned to your committee folder. Please complete initial scoring by next Monday.",
          },
        ],
        mockCategory: "Committee/Admin",
        mockUrgency: "Medium",
        mockActionNeeded: true,
        mockDeadline: daysAhead(6),
        mockAiExplanation: "Graduate admissions committee review assignments distributed.",
        mockIsRead: false,
      },
      {
        externalThreadId: "th-mock-019",
        subject: "Midterm Make-up Exam Proctor Request (Illness)",
        participants: ["Emily Carter <ecarter@student.univ.edu>", "Dr. Eleanor Vance <evance@univ.edu>"],
        lastMessageAt: hoursAgo(36),
        messages: [
          {
            sender: "Emily Carter <ecarter@student.univ.edu>",
            senderIsFaculty: false,
            sentAt: hoursAgo(36),
            body: "Dr. Vance, I was in urgent care on Tuesday during our exam. I have uploaded doctor notes to the health portal and hope to schedule a make-up session.",
          },
        ],
        mockCategory: "Examination",
        mockUrgency: "High",
        mockActionNeeded: true,
        mockDeadline: daysAhead(3),
        mockAiExplanation: "Student requesting make-up midterm exam after medically excused absence.",
        mockIsRead: false,
      },
      {
        externalThreadId: "th-mock-020",
        subject: "University Weekly Digest & Campus Announcements #41",
        participants: ["Campus Communications <newsletter@univ.edu>"],
        lastMessageAt: daysAgo(1),
        messages: [
          {
            sender: "Campus Communications <newsletter@univ.edu>",
            senderIsFaculty: false,
            sentAt: daysAgo(1),
            body: "Weekly roundup: President's town hall recap, parking lot C repaving schedule, dining hall fall menu additions, and library research workshops.",
          },
        ],
        mockCategory: "Other",
        mockUrgency: "Low",
        mockActionNeeded: false,
        mockDeadline: null,
        mockAiExplanation: "General university-wide weekly newsletter and general campus bulletins.",
        mockIsRead: true,
      },
      {
        externalThreadId: "th-mock-021",
        subject: "IT Security Advisory: Mandatory Duo 2FA Device Migration",
        participants: ["Information Security Office <infosec@univ.edu>"],
        lastMessageAt: daysAgo(3),
        messages: [
          {
            sender: "Information Security Office <infosec@univ.edu>",
            senderIsFaculty: false,
            sentAt: daysAgo(3),
            body: "All faculty and staff must upgrade to the new Duo Universal Prompt before next month. No immediate action required if already using the mobile app.",
          },
        ],
        mockCategory: "Other",
        mockUrgency: "Low",
        mockActionNeeded: false,
        mockDeadline: null,
        mockAiExplanation: "Campus IT routine security notice regarding multi-factor authentication upgrade.",
        mockIsRead: true,
      },
      {
        externalThreadId: "th-mock-022",
        subject: "Call for Papers: IEEE International Symposium on Learning Technologies",
        participants: ["IEEE CFP Coordinator <cfp-noreply@ieee-events.org>"],
        lastMessageAt: daysAgo(5),
        messages: [
          {
            sender: "IEEE CFP Coordinator <cfp-noreply@ieee-events.org>",
            senderIsFaculty: false,
            sentAt: daysAgo(5),
            body: "Submissions are open for the 28th annual conference in Vancouver. Research track, workshop proposals, and student poster session deadlines announced.",
          },
        ],
        mockCategory: "Other",
        mockUrgency: "Low",
        mockActionNeeded: false,
        mockDeadline: null,
        mockAiExplanation: "External conference call for papers solicitation.",
        mockIsRead: true,
      },
    ];

    return mockThreads;
  }
}
