/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FollowUpRouteImport } from './routes/follow-up'
import { Route as OtherRouteImport } from './routes/other'
import { Route as ThreadsIndexRouteImport } from './routes/threads.index'
import { Route as ThreadsThreadIdRouteImport } from './routes/threads.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpRoute = FollowUpRouteImport.update({
  id: '/follow-up',
  path: '/follow-up',
  getParentRoute: () => rootRouteImport,
} as any)
const OtherRoute = OtherRouteImport.update({
  id: '/other',
  path: '/other',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsIndexRoute = ThreadsIndexRouteImport.update({
  id: '/threads/',
  path: '/threads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsThreadIdRoute = ThreadsThreadIdRouteImport.update({
  id: '/threads/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/follow-up': typeof FollowUpRoute
  '/other': typeof OtherRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/threads/': typeof ThreadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/follow-up': typeof FollowUpRoute
  '/other': typeof OtherRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/threads': typeof ThreadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/follow-up': typeof FollowUpRoute
  '/other': typeof OtherRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/threads/': typeof ThreadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/follow-up' | '/other' | '/threads/$threadId' | '/threads/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/follow-up' | '/other' | '/threads/$threadId' | '/threads'
  id:
    | '__root__'
    | '/'
    | '/follow-up'
    | '/other'
    | '/threads/$threadId'
    | '/threads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FollowUpRoute: typeof FollowUpRoute
  OtherRoute: typeof OtherRoute
  ThreadsThreadIdRoute: typeof ThreadsThreadIdRoute
  ThreadsIndexRoute: typeof ThreadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-up': {
      id: '/follow-up'
      path: '/follow-up'
      fullPath: '/follow-up'
      preLoaderRoute: typeof FollowUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/other': {
      id: '/other'
      path: '/other'
      fullPath: '/other'
      preLoaderRoute: typeof OtherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/': {
      id: '/threads/'
      path: '/threads'
      fullPath: '/threads/'
      preLoaderRoute: typeof ThreadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/$threadId': {
      id: '/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof ThreadsThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FollowUpRoute: FollowUpRoute,
  OtherRoute: OtherRoute,
  ThreadsThreadIdRoute: ThreadsThreadIdRoute,
  ThreadsIndexRoute: ThreadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
